name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.8
  - pip
  - numpy=1.21.6
  - spacy=3.5.3
  - flask=2.2.5
  - pip:
    - gunicorn==20.1.0
    - python-telegram-bot[job-queue]==20.6
    - aiohttp==3.8.5
    - googlemaps==4.2.0
    - unidecode==1.3.6
    - python-dotenv==1.0.0
    - openai==0.28.1
    - lingua-language-detector==1.3.2
    - transformers==4.31.0
    - sentence-transformers==2.2.2
    - scikit-learn==1.0.2
    - deep-translator==1.11.1
    - pytz==2023.3
    - requests==2.31.0
    - pandas==1.5.3
    - deeppavlov==1.1.0
    - tqdm==4.65.0
    - torch==1.13.1
    - geopy==2.3.0
