[build-system]
requires = ["setuptools>=69.0.3", "wheel>=0.42.0"]
build-backend = "setuptools.build_meta"

[project]
name = "neptun"
version = "1.0.0"
description = "Telegram bot for monitoring"
requires-python = ">=3.9.18"
dependencies = []
