services:
  - type: web
    name: neptun
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install wheel==0.41.2 setuptools==68.0.0
      pip install numpy==1.24.3
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
      python -m spacy download uk_core_news_sm
    startCommand: gunicorn wsgi:app --config gunicorn_config.py
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: "3.10.8"
      - key: PIP_DEFAULT_TIMEOUT
        value: "100"
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: LANG
        value: "uk_UA.UTF-8"
      - key: TZ
        value: "Europe/Kiev"
