services:
  - type: web
    name: neptun
    env: python
    buildCommand: |
      curl -O https://www.python.org/ftp/python/3.10.8/Python-3.10.8.tgz
      tar -xzf Python-3.10.8.tgz
      cd Python-3.10.8
      ./configure --enable-optimizations
      make -j $(nproc)
      sudo make altinstall
      cd ..
      python3.10 -m pip install --upgrade pip
      python3.10 -m pip install wheel==0.41.2 setuptools==68.0.0
      python3.10 -m pip install numpy==1.21.6
      python3.10 -m pip install -r requirements.txt
      python3.10 -m spacy download uk_core_news_sm
    startCommand: gunicorn wsgi:app --config gunicorn_config.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: "3.10.8"
      - key: PIP_DEFAULT_TIMEOUT
        value: "100"
