services:
  - type: web
    name: neptun
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python -m spacy download uk_core_news_sm
    startCommand: gunicorn wsgi:app --config gunicorn_config.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: "3.10.8"
