services:
  - type: web
    name: neptun
    env: python
    buildCommand: pip install -r requirements.txt && python -m spacy download uk_core_news_sm
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
