services:
  - type: web
    name: neptun
    env: python
    region: frankfurt
    plan: free
    runtime: "python"
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir setuptools==68.0.0 wheel==0.41.2
      pip install --no-cache-dir numpy==1.24.3
      pip install --no-cache-dir -r requirements.txt
      python -m spacy download en_core_web_sm
      python -m spacy download uk_core_news_sm
    startCommand: gunicorn wsgi:app --config gunicorn_config.py
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: "3.10.8"
      - key: PIP_DEFAULT_TIMEOUT
        value: "300"
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: LANG
        value: "uk_UA.UTF-8"
      - key: TZ
        value: "Europe/Kiev"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
      - key: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
        value: "python"
      - key: PIP_NO_BINARY
        value: ":all:"
